categories = {
    "processor": "Processor",
    "Processors": "Processor",
    "Graphics": "Video card",
    "video-cards-64": "Video card",
    "Motherboards": "Motherboard",
    "motherboards": "Motherboard",
    "motherboards-61": "Motherboard",
    "processors-62": "Processor",
    "processor": "Processor",
    "graphics-card": "Video card",
    "motherboard": "Motherboard",
    "Graphics": "Video card",
    "graphic": "Video card",
    "processors": "Processor",
    "video-cards": "Video card",
}