categories = {
    "processor": "Processor",
    "Processors": "Processor",
    "Graphics": "Video card",
    "video-cards-64": "Video card",
    "Motherboards": "Motherboard",
    "motherboards": "Motherboard",
    "motherboards-61": "Motherboard",
    "processors-62": "Processor",
    "processor": "Processor",
    "graphics-card": "Video card",
    "motherboard": "Motherboard",
    "Graphics": "Video card",
    "graphic": "Video card",
    "processors": "Processor",
    "video-cards": "Video card",
    "power-supply": "Power supply",
    "internal-storage": "Storage",
    "pc-cases": "Chassis",
    "cpu-coolers": "CPU Cooler",
    "Rams": "Memory",
    "Coolers": "CPU Cooler",
    "Power": "Power supply",
    "Solid": "Storage",
    "Hard": "Storage",
    "Cases": "Chassis",
    "memory": "Memory",
    "chassis": "Chassis",
    "hard-drive": "Storage",
    "ssd-m-2": "Storage",
    "chassis-65": "Chassis",
    "cooling-systems-aircooling-system-92": "CPU Cooler",
    "cooling-systems-aio-liquid-cooling-system-89": "CPU Cooler",
    "memory-modules-57": "Memory",
    "storage-devices-solid-state-drive-72": "Storage",
    "storage-devices-hard-disk-106": "Storage",
    "power-sources-63": "Power supply",
    "cpu": "CPU Cooler",
    "pc": "Chassis",
    "power": "Power supply",
    "hard": "Storage",
    "solid": "Storage",
    "power-sources": "Power supply",
    "memory-modules": "Memory",
    "power-sources": "Power supply",
    "cooling-systems": "CPU Cooler",
    
}